### ISSUE TITLE
Great research!  But, what cable are you using?

### ISSUE THREAD

**Issue by sbarthelmess** [Shotgun167/simplesolarmon#1]
I purchased a CC-USB-RS485-150U-V2.0 cable through Amazon (seemingly the same one they advertise at PowMr).  I get a /dev/ttyACM0 device (which from https://rfc1149.net/blog/2013/03/05/what-is-the-difference-between-devttyusbx-and-devttyacmx/ should just be a straight USB->RS232).  Potentially I can kill the cdc_acm driver and go with usbserial (currently researching).

I'm connecting to the RS485-1 port on the PowMr inverter.  If I set it to /dev/ttyACM0 I just get "No communication with the instrument (no answer)".    Any thoughts?

At least can you help the rest of us and let us know which cable you are using?  Thanks!

**Comment by Shotgun167** [comment]
I just used an old cable pulled from my junk drawer.  It was working just fine, and then I tried to scan the other addresses to see what other info I could gather.  On one of the forums, I read that trying to read an address above a certain range would brick the communications section of the device.  Seems about right to me, since I've gotten nothing out of it since I did the scan.
